# Generated by Django 5.1.6 on 2025-03-20 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='progresstracker',
            name='goal_weight',
            field=models.FloatField(default=70.0),
            preserve_default=False,
        ),
    ]
