# Generated by Django 5.1.6 on 2025-03-20 02:22

from django.db import migrations, models  # ✅ Added models for the new field

class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0002_progresstracker_goal_weight'),
    ]

    operations = [  # ✅ Fixed indentation
        migrations.AddField(
            model_name='nutritionplan',
            name='meal_name',
            field=models.CharField(max_length=255, default='Meal'),  # ✅ Temporary default value
        ),
    ]