# Generated by Django 5.1.6 on 2025-03-20 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0004_alter_nutritionplan_meal_name_mealplan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='fitness_level',
            field=models.CharField(default='Beginner', max_length=100),
        ),
    ]
