# Generated by Django 5.1.6 on 2025-03-20 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0005_alter_userprofile_fitness_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.IntegerField(default=18),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='goal',
            field=models.CharField(default='weight_loss', max_length=100),
        ),
    ]
