# Generated by Django 5.1.6 on 2025-03-21 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0007_workoutlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkoutLog',
        ),
    ]
