# Generated by Django 5.1.7 on 2025-04-05 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='customuser',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='userquestionnaire',
            name='body_type',
            field=models.CharField(default='Average', max_length=255),
        ),
        migrations.AlterField(
            model_name='userquestionnaire',
            name='daily_caloric_need',
            field=models.IntegerField(default=2000),
        ),
        migrations.AlterField(
            model_name='userquestionnaire',
            name='dietary_restrictions',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AlterField(
            model_name='userquestionnaire',
            name='fitness_goals',
            field=models.CharField(default='General health', max_length=255),
        ),
        migrations.AlterField(
            model_name='userquestionnaire',
            name='macronutrient_ratio',
            field=models.CharField(default='Balanced', max_length=255),
        ),
        migrations.AlterField(
            model_name='userquestionnaire',
            name='sleep_hours',
            field=models.IntegerField(default=7),
        ),
        migrations.AlterField(
            model_name='userquestionnaire',
            name='supplements',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AlterField(
            model_name='userquestionnaire',
            name='water_intake',
            field=models.CharField(default='2 liters', max_length=255),
        ),
        migrations.AlterField(
            model_name='userquestionnaire',
            name='work_schedule',
            field=models.CharField(default='9-5 Job', max_length=255),
        ),
        migrations.AlterField(
            model_name='userquestionnaire',
            name='workout_frequency',
            field=models.CharField(default='3 days/week, Moderate', max_length=255),
        ),
    ]
