# Generated by Django 5.1.6 on 2025-04-13 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_delete_user_customuser_age_customuser_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userquestionnaire',
            name='daily_caloric_need',
        ),
        migrations.AddField(
            model_name='userquestionnaire',
            name='activity_level',
            field=models.CharField(choices=[('sedentary', 'Sedentary'), ('light', 'Lightly active'), ('moderate', 'Moderately active'), ('active', 'Active'), ('very_active', 'Very active')], default='moderate', max_length=50),
        ),
        migrations.AddField(
            model_name='userquestionnaire',
            name='cooking_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userquestionnaire',
            name='current_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userquestionnaire',
            name='daily_budget',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userquestionnaire',
            name='diet',
            field=models.CharField(default='omnivore', max_length=50),
        ),
        migrations.AddField(
            model_name='userquestionnaire',
            name='intolerances',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='userquestionnaire',
            name='target_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userquestionnaire',
            name='fitness_goals',
            field=models.CharField(choices=[('lose', 'Lose Weight'), ('maintain', 'Maintain Weight'), ('gain', 'Gain Weight')], default='maintain', max_length=50),
        ),
        migrations.AlterField(
            model_name='userquestionnaire',
            name='macronutrient_ratio',
            field=models.CharField(choices=[('balanced', 'Balanced'), ('high_protein', 'High Protein'), ('low_carb', 'Low Carb'), ('low_fat', 'Low Fat')], default='balanced', max_length=50),
        ),
    ]
