# Generated by Django 5.1.6 on 2025-04-13 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_remove_userquestionnaire_daily_caloric_need_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquestionnaire',
            name='height',
            field=models.FloatField(default=170.0, help_text='Height in cm'),
        ),
    ]
