# Generated by Django 5.1.6 on 2025-04-13 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_userquestionnaire_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquestionnaire',
            name='target_calories',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
