# Generated by Django 5.1.7 on 2025-03-20 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuestionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fitness_goals', models.CharField(blank=True, max_length=255)),
                ('body_type', models.CharField(blank=True, max_length=255)),
                ('daily_caloric_need', models.IntegerField(blank=True, null=True)),
                ('workout_frequency', models.CharField(blank=True, max_length=255)),
                ('macronutrient_ratio', models.CharField(blank=True, max_length=255)),
                ('dietary_restrictions', models.CharField(blank=True, max_length=255)),
                ('sleep_hours', models.IntegerField(blank=True, null=True)),
                ('work_schedule', models.CharField(blank=True, max_length=255)),
                ('supplements', models.CharField(blank=True, max_length=255)),
                ('water_intake', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
